const APP_CONSTANTS = {
    TASK_FORM_MODE_EDIT: 'edit',
    TASK_FORM_MODE_CREATE: 'create',
    TASK_FORM_CREATE_TITLE: 'Add New Task',
    TASK_FORM_EDIT_TITLE: 'Edit Task',
    TASK_FORM_SAVE: 'Save',
    TASK_FORM_UPDATE: 'Update',
    STACK_NAVIGATION_SCREEN_HOME: 'Home',
    STACK_NAVIGATION_SCREEN_CREATE_TASK: 'CreateTask',
    STACK_NAVIGATION_SCREEN_EDIT_TASK: 'EditTask',
    SCREEN_HOME_TITLE: 'Tasks',
    SLICE_NAME_TASKS: 'tasks',
    SLICE_NAME_USER: 'user',
    SIGN_IN_USER: 'user/signInUser',
    SIGN_UP_USER: 'user/signUpUser',
    LOGOUT_USER: 'user/logoutUser',
    FETCH_TASKS: 'tasks/fetchTasks',
    DELETE_TASK: 'tasks/deleteTask',
    ADD_TASK: 'tasks/addTask',
    UPDATE_TASK: 'tasks/updateTask',
    TOGGLE_TASK_COMPLETION: 'tasks/toggleTaskCompletion',
    STORAGE_KEY_USER_ID: 'userId',
}

export default APP_CONSTANTS;